### ISSUE TITLE
Runing and moving camera is with delays.

### ISSUE THREAD

**Issue by SilencerXX** [APK-Multi-Games/SkyLaboratory-Remade#1]
Hello.
After last update having problem with moving, arround, i has become unresponsive. Like delay before any step or movment.

**Comment by raziel23x** [comment]
Are you playing with or without a resource packs as i am not having any issue with it and i am not playing with any resource packs

**Comment by raziel23x** [comment]
Also did you create a new world not using the old one

**Comment by raziel23x** [comment]
Fixed with 0.0.1.0 release closing issue
