### ISSUE TITLE
Possible Memory Leak in modpack

### ISSUE THREAD

**Issue by raziel23x** [APK-Multi-Games/SkyLaboratory-Remade#2]
There is a memory leak somewhere in the modpack.

Need logs files to help track down memory leak

**Comment by HellishPirate** [comment]
[latest.log](https://github.com/APK-Multi-Games/SkyLaboratory-Remade/files/2431611/latest.log)

**Comment by Rafii2198** [comment]
Debug log: https://drive.google.com/open?id=17qXnoDvayRN_wXKpDPKhZU4BiLizBUf7

[latest.log](https://github.com/APK-Multi-Games/SkyLaboratory-Remade/files/2431614/latest.log)

**Comment by MARTIKRISO** [comment]
[suff.zip](https://github.com/APK-Multi-Games/SkyLaboratory-Remade/files/2431657/suff.zip)

**Comment by Rahlal** [comment]
[latest.log](https://github.com/APK-Multi-Games/SkyLaboratory-Remade/files/2431659/latest.log)

**Comment by raziel23x** [comment]
[latest.log](https://github.com/APK-Multi-Games/SkyLaboratory-Remade/files/2431675/latest.log)

**Comment by KendirkRS** [comment]
So yeah after some testing in 0.0.1.1 it seams the memory leak issue was/is cause mostly by ThaumicJEI mines disabled and i have been in game with 20 mins with no freezing from the start at all

**Comment by raziel23x** [comment]
Seems of fixed itself after several mods updated
