### ISSUE TITLE
EMC Value

### ISSUE THREAD

**Issue by Eagle798** [APK-Multi-Games/SkyLaboratory-Remade#3]
Hi, i've notice that the emc value are incorrect when burned to an energy condenser or transmutation table the only thinks didnt change is cobbleston, glass, sand that have 1 of EMC value

**Comment by KendirkRS** [comment]
Yes this is Called EMC lost if you seen in then EMC section in tooltip and see in the (bracketsnumbers) that is what you will get rather than the white EMC base number
